const
  ZMUNITMAX = 48;
  ZMUnitNames: array [0..ZMUNITMAX-1] of string = (
    'ZipMstr', 'ZMArgSplit', 'ZMBaseOpr', 'ZMBody', 'ZMCoDec', 'ZMCommand',
   'ZMCompat', 'ZMCore', 'ZMCRC', 'ZMCtx', 'ZMDelZip', 'ZMDlg', 'ZMDllLoad',
   'ZMDrv', 'ZMEngine', 'ZMEntryReader', 'ZMFileOpr', 'ZMFStream',
   'ZMHandler', 'ZMLister', 'ZMMatch', 'ZMMFStream', 'ZMMisc', 'ZMMsg',
   'ZMOprCore', 'ZMOprDeflate', 'ZMOprDel', 'ZMOprDll', 'ZMOprFile',
   'ZMOprMerge', 'ZMOprMod', 'ZMOprMsgStr', 'ZMOprUnzip', 'ZMReg', 'ZMSFXInt',
   'ZMStructs', 'ZMUnzipOpr', 'ZMUTF8', 'ZMUtils', 'ZMWinFuncs', 'ZMXcpt',
   'ZMZipBase', 'ZMZipDirectory', 'ZMZipEOC', 'ZMZipMulti', 'ZMZipReader',
   'ZMZipWriter', 'ZMZLibExApi');
