// ZipMaster configuration 1.9.1.x
// Configuration options - rebuild if changed

//__ USE_COMPRESSED_STRINGS - undefine to use ResourceStrings
{$Define USE_COMPRESSED_STRINGS}

//__ STATIC_LOAD_DELZIP_DLL - define to statically load dll
//{$DEFINE STATIC_LOAD_DELZIP_DLL}

//__ SINGLE_ZIPMASTER_VERSION - define if no other version is installed
//{$DEFINE SINGLE_ZIPMASTER_VERSION}

//__ SUPPORT_OLD_WINDOWS - define if must run on Windows (95?),98,ME
//{$DEFINE SUPPORT_OLD_WINDOWS}


